packages:
  # all apps in direct subdirs of apps/
  - 'src/apps/**/*'
  # all libs in direct subdirs of shared/
  - 'src/shared/**/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
